//
// Model200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Model200: Codable, JSONEncodable, Hashable {

    public var coord: Coord?
    /** (more info Weather condition codes) */
    public var weather: [Weather]?
    /** Internal parameter */
    public var base: String?
    public var main: Main?
    /** Visibility, meter */
    public var visibility: Int?
    public var wind: Wind?
    public var clouds: Clouds?
    public var rain: Rain?
    public var snow: Snow?
    /** Time of data calculation, unix, UTC */
    public var dt: Int?
    public var sys: Sys?
    /** City ID */
    public var id: Int?
    public var name: String?
    /** Internal parameter */
    public var cod: Int?

    public init(coord: Coord? = nil, weather: [Weather]? = nil, base: String? = nil, main: Main? = nil, visibility: Int? = nil, wind: Wind? = nil, clouds: Clouds? = nil, rain: Rain? = nil, snow: Snow? = nil, dt: Int? = nil, sys: Sys? = nil, id: Int? = nil, name: String? = nil, cod: Int? = nil) {
        self.coord = coord
        self.weather = weather
        self.base = base
        self.main = main
        self.visibility = visibility
        self.wind = wind
        self.clouds = clouds
        self.rain = rain
        self.snow = snow
        self.dt = dt
        self.sys = sys
        self.id = id
        self.name = name
        self.cod = cod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coord
        case weather
        case base
        case main
        case visibility
        case wind
        case clouds
        case rain
        case snow
        case dt
        case sys
        case id
        case name
        case cod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(coord, forKey: .coord)
        try container.encodeIfPresent(weather, forKey: .weather)
        try container.encodeIfPresent(base, forKey: .base)
        try container.encodeIfPresent(main, forKey: .main)
        try container.encodeIfPresent(visibility, forKey: .visibility)
        try container.encodeIfPresent(wind, forKey: .wind)
        try container.encodeIfPresent(clouds, forKey: .clouds)
        try container.encodeIfPresent(rain, forKey: .rain)
        try container.encodeIfPresent(snow, forKey: .snow)
        try container.encodeIfPresent(dt, forKey: .dt)
        try container.encodeIfPresent(sys, forKey: .sys)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(cod, forKey: .cod)
    }
}

