//
// Sys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Sys: Codable, JSONEncodable, Hashable {

    /** Internal parameter */
    public var type: Int?
    /** Internal parameter */
    public var id: Int?
    /** Internal parameter */
    public var message: Double?
    /** Country code (GB, JP etc.) */
    public var country: String?
    /** Sunrise time, unix, UTC */
    public var sunrise: Int?
    /** Sunset time, unix, UTC */
    public var sunset: Int?

    public init(type: Int? = nil, id: Int? = nil, message: Double? = nil, country: String? = nil, sunrise: Int? = nil, sunset: Int? = nil) {
        self.type = type
        self.id = id
        self.message = message
        self.country = country
        self.sunrise = sunrise
        self.sunset = sunset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case message
        case country
        case sunrise
        case sunset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(sunrise, forKey: .sunrise)
        try container.encodeIfPresent(sunset, forKey: .sunset)
    }
}

