//
// Wind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Wind: Codable, JSONEncodable, Hashable {

    /** Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour. */
    public var speed: Double?
    /** Wind direction, degrees (meteorological) */
    public var deg: Int?

    public init(speed: Double? = nil, deg: Int? = nil) {
        self.speed = speed
        self.deg = deg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case speed
        case deg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(speed, forKey: .speed)
        try container.encodeIfPresent(deg, forKey: .deg)
    }
}

