//
// CurrentWeatherDataAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CurrentWeatherDataAPI {

    /**
     Call current weather data for one location
     
     - parameter q: (query) For the query value, type the city name and optionally the country code divided by comma; use ISO 3166 country codes. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func currentWeatherData(q: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Model200?, _ error: Error?) -> Void)) -> RequestTask {
        return currentWeatherDataWithRequestBuilder(q: q).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Call current weather data for one location
     - GET /weather
     - Get the current weather info
     - API Key:
       - type: apiKey appid (QUERY)
       - name: app_id
     - parameter q: (query) For the query value, type the city name and optionally the country code divided by comma; use ISO 3166 country codes. (optional)
     - returns: RequestBuilder<Model200> 
     */
    open class func currentWeatherDataWithRequestBuilder(q: String? = nil) -> RequestBuilder<Model200> {
        let localVariablePath = "/weather"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Model200>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
